# Generated by Django 6.0.3 on 2026-03-05 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_workouttemplate_workouttemplateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used to generate this workout instance (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_workouts', to='main_app.workouttemplate'),
        ),
    ]
