"""
Django settings for hw_app project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

load_dotenv(override=True)

import dj_database_url  

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# DEBUG must be defined before SECRET_KEY so non-debug deploys cannot fall back to a dev key.
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"

_django_secret_key = (os.getenv("DJANGO_SECRET_KEY") or "").strip()
if not DEBUG and not _django_secret_key:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be set when DEBUG is False. "
        "Set DJANGO_SECRET_KEY in the environment for production/staging."
    )
SECRET_KEY = _django_secret_key or "dev-insecure-key"

# Bare hostnames only (no scheme). Example: myapp.up.railway.app,localhost
_allowed_hosts_env = (os.getenv("DJANGO_ALLOWED_HOSTS") or "").strip()
if not _allowed_hosts_env:
    raise ImproperlyConfigured(
        "DJANGO_ALLOWED_HOSTS must be set. "
        "Provide a comma-separated list of bare hostnames (no scheme), e.g. myapp.up.railway.app,localhost"
    )
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]

# Full origin URLs with scheme (no trailing slash). Example: https://myapp.netlify.app,http://localhost:5173
_cors_origins_env = (os.getenv("CORS_ALLOWED_ORIGINS") or "").strip()
if not _cors_origins_env:
    raise ImproperlyConfigured(
        "CORS_ALLOWED_ORIGINS must be set. "
        "Provide a comma-separated list of full origin URLs, e.g. https://myapp.netlify.app,http://localhost:5173"
    )
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins_env.split(",") if o.strip()]

# Full origin URLs with scheme (no trailing slash). Controls trusted origins for CSRF (admin panel, session views).
_csrf_origins_env = (os.getenv("CSRF_TRUSTED_ORIGINS") or "").strip()
if not _csrf_origins_env:
    raise ImproperlyConfigured(
        "CSRF_TRUSTED_ORIGINS must be set. "
        "Provide a comma-separated list of full origin URLs, e.g. https://myapp.up.railway.app,http://localhost:5173"
    )
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins_env.split(",") if o.strip()]

from datetime import timedelta

_jwt_access_minutes = int(os.getenv("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", "60"))
_jwt_refresh_days = int(os.getenv("JWT_REFRESH_TOKEN_LIFETIME_DAYS", "7"))

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=_jwt_access_minutes),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=_jwt_refresh_days),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'main_app',
    'rest_framework_simplejwt',
    'corsheaders'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ]
}

# Per-user resource limits. Override via environment variables if needed.
USER_MAX_WORKOUT_TEMPLATES = int(os.getenv("USER_MAX_WORKOUT_TEMPLATES", "25"))
USER_MAX_WORKOUT_PLANS = int(os.getenv("USER_MAX_WORKOUT_PLANS", "25"))
USER_MAX_WORKOUTS = int(os.getenv("USER_MAX_WORKOUTS", "250"))

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hw_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hw_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")

_db_ssl_env = os.getenv("DATABASE_SSL_REQUIRE")
if _db_ssl_env is not None:
    _database_ssl_require = _db_ssl_env.strip().lower() in ("1", "true", "yes", "on")
else:
    # Prefer TLS for non-debug deploys; local SQLite/dev often unset or non-TLS.
    _database_ssl_require = not DEBUG

DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=_database_ssl_require,
    )
}

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # NEW

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",  # NEW
    },
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
